[tool.black]
#line-length = 99 # override black's default line-length
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black" 
force_single_line = true
force_sort_within_sections = true
order_by_type = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'ftq.settings'
#python_files = test_*.py *_test.py