# Generated by Django 4.0.1 on 2022-01-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_server_key_salt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_server_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
